#!/bin/bash

#taking arguments and use for loop to iterate untill end of arguments
for arg in "$@"
do 
	if [ -d "${arg}" ]; then
	  #if the argument is a directory, it will recursively print names of ascii file.
		grep -rLP '[^\x80-\xFF]' $arg 	
	else
	  #if the argument is a file
		if [[ "$(file "$arg")" =~ ': utf-8 text'$ ]]; then
			#if it is an ascii file, pipe it to ascii.txt
			 echo $ $arg
		fi	
	fi
done	
